# Generated by Django 5.2.7 on 2025-11-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_board_shared_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='board_type',
            field=models.CharField(choices=[('task', 'Task Board'), ('note', 'Note Board')], default='task', max_length=10),
        ),
    ]
