# Generated by Django 5.2.7 on 2025-10-14 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_list_delete_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='description',
        ),
        migrations.AlterField(
            model_name='list',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='api.list')),
            ],
        ),
    ]
