# Generated by Django 5.2.7 on 2025-11-16 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_board_board_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='board_type',
        ),
    ]
