# Generated by Django 5.2.7 on 2025-11-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_board_board_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='card',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='list',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
