# Generated by Django 5.2.5 on 2025-12-02 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_activitylog_card_alter_activitylog_list_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='guest_namne',
            new_name='guest_name',
        ),
    ]
